image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - staging
    - production

staging:
    type: deploy
    stage: staging
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=run-nodejs-bookstore --api-key=5d6c3980-492a-4530-9277-4cf47dd86287
    only:
        - staging

production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=run-nodejs-bookstore --api-key=5d6c3980-492a-4530-9277-4cf47dd86287
    only:
        - master